networks:
  sim-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.1.0/24

services:
  ns3:
    build:
      context: ./ns-3
      args:
        - BUILD_PROF=debug
    container_name: ns3
    networks:
      sim-net:
        ipv4_address: 10.99.1.11
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./ns-3/scripts:/app/scripts
      - ./ns-3/scratch:/app/ns-3/scratch/scripts
    environment:
      - BUILD_PROF=debug
  client:
    image: ghcr.io/astral-sh/uv:alpine
    container_name: client
    networks:
      sim-net:
        ipv4_address: 10.99.1.22
    depends_on:
      - ns3
    environment:
      SERVER_IP: "10.99.1.11"
    volumes:
      - ./client:/app
    command: "tail -f /dev/null"
