services:

  ns3:
    build:
      context: ./ns3
      dockerfile: Dockerfile
    container_name: ns3-simulator
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/workspace

  client:
    image: postman/newman:alpine
    container_name: client
    depends_on:
      - ns3
    volumes:
      - ./client:/etc/newman
    command: