networks:
  sim-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.0.0/24

services:
  ns3:
    build:
      context: ./ns-3
    container_name: ns3
    networks:
      sim-net:
        ipv4_address: 10.99.1.11
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./ns3-node/scripts:/app/scripts
      - ./ns3-node/scratch:/app/ns-3/scratch/scripts
  client:
    image: ghcr.io/astral-sh/uv:alpine
    container_name: client
    networks:
      sim-net:
        ipv4_address: 10.99.1.22
    depends_on:
      - ns3
    environment:
      SERVER_IP: "http://10.99.1.11"
    volumes:
      - ./client:/app
    command: "tail -f /dev/null"
